version: '3.8'

# ❗ NOTES: 
#   1. With NUXT server-side runtime envs you need to add NUXT_
#      - eg. NUXT_OPENAI_API_KEY=xyz (✓)
#      - eg. OPENAI_API_KEY=xyz      (✗)
#   
#   2. While using URLs, be careful with extra qoutes
#      - eg. NUXT_API_ENDPOINT=http://localhost:3000/api/v1/prediction/6fac0499-e1bf-498f-a07d-89d52d8ac209   (✓)
#      - eg. NUXT_API_ENDPOINT='http://localhost:3000/api/v1/prediction/6fac0499-e1bf-498f-a07d-89d52d8ac209' (✗)

services:
  nuxt:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: docker.io/jeetmetapercept/quizzee:latest
    ports:
      - "80:3000"
    # env_file:
    #   - .env
    environment:
      - NODE_ENV=production
      - PROJECT_NAME=Quizzee
      - BASE_URL=https://quizzee.proximabiz.net
      # Supabase https://supabase.com/dashboard/project/iyhffqunapidrefhlhgw
      - SUPABASE_URL=https://iyhffqunapidrefhlhgw.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5aGZmcXVuYXBpZHJlZmhsaGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTIwNDk5MDYsImV4cCI6MjAwNzYyNTkwNn0.rMMmcKNdTh-a41EbenT9Ho04dj0X1u8Bw0M5QYq_ybQ
      # OPEN AI
      - OPENAI_API_KEY=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
      # UAMAI
      - NUXT_PUBLIC_UMAMI_HOST=https://quizzee.proximabiz.net
      - NUXT_PUBLIC_UMAMI_ID=c8f08896-1723-4cd7-bd28-87b180d37cc4